### ISSUE TITLE
creating button to copy the quote to clipboard

### ISSUE THREAD

**Issue by atmaram-kambli** [priyanshuarora595/Random-Quote-Generator#6]
Hey, I can add feature to your project , that of copying the quote generated to the clipboard.
Let me know if can work on this. For Hacktoberfest

**Comment by priyanshuarora595** [comment]
sure

**Comment by priyanshuarora595** [comment]
> Hey, I can add feature to your project , that of copying the quote generated to the clipboard. Let me know if can work on this. For Hacktoberfest

sure, go ahead. Do the changes in the code and create a Pull Request, i'll merge it after reviewing.
for now, i am closing this thread as this is not an issue.
